"""Celery task that periodically reloads Groq API keys from env.

Runs on the celery_beat schedule. If `GROQ_API_KEYS` has changed since the
worker started, the task:
  1. Swaps in the new key list,
  2. Resets the round-robin index to 0,
  3. Clears the in-process LRU cache (so stale narrations generated by the
     old key set aren't served back).

This means rotating keys is an env-edit + `docker compose restart celery_beat`
away — the API workers don't need to bounce.

Note: each Python *process* (each uvicorn worker, each celery worker) keeps
its own client instance. The beat task only fires inside celery_beat. To
propagate the rotation across all processes, hit the admin endpoint
`POST /api/v1/admin/llm/refresh` from a sidecar or restart the workers.
"""
from __future__ import annotations

import logging

from app.services.llm.groq_client import get_groq_client
from app.tasks.celery_app import celery_app

logger = logging.getLogger(__name__)


@celery_app.task(name="app.tasks.llm_refresh.refresh_groq_keys")
def refresh_groq_keys() -> dict:
    client = get_groq_client()
    result = client.reload_keys_if_changed()
    if result.get("changed"):
        logger.info(
            "[llm_refresh] keys rotated: %d active, cleared %d cached narrations",
            result["keys"],
            result["cache_cleared"],
        )
    return result
